// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lidar_schema.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_lidar_5fschema_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_lidar_5fschema_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_lidar_5fschema_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_lidar_5fschema_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_lidar_5fschema_2eproto;
namespace ds3dmsg {
class LidarPointCloud;
struct LidarPointCloudDefaultTypeInternal;
extern LidarPointCloudDefaultTypeInternal _LidarPointCloud_default_instance_;
class Point;
struct PointDefaultTypeInternal;
extern PointDefaultTypeInternal _Point_default_instance_;
}  // namespace ds3dmsg
PROTOBUF_NAMESPACE_OPEN
template<> ::ds3dmsg::LidarPointCloud* Arena::CreateMaybeMessage<::ds3dmsg::LidarPointCloud>(Arena*);
template<> ::ds3dmsg::Point* Arena::CreateMaybeMessage<::ds3dmsg::Point>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace ds3dmsg {

// ===================================================================

class LidarPointCloud final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ds3dmsg.LidarPointCloud) */ {
 public:
  inline LidarPointCloud() : LidarPointCloud(nullptr) {}
  ~LidarPointCloud() override;
  explicit PROTOBUF_CONSTEXPR LidarPointCloud(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LidarPointCloud(const LidarPointCloud& from);
  LidarPointCloud(LidarPointCloud&& from) noexcept
    : LidarPointCloud() {
    *this = ::std::move(from);
  }

  inline LidarPointCloud& operator=(const LidarPointCloud& from) {
    CopyFrom(from);
    return *this;
  }
  inline LidarPointCloud& operator=(LidarPointCloud&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LidarPointCloud& default_instance() {
    return *internal_default_instance();
  }
  static inline const LidarPointCloud* internal_default_instance() {
    return reinterpret_cast<const LidarPointCloud*>(
               &_LidarPointCloud_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(LidarPointCloud& a, LidarPointCloud& b) {
    a.Swap(&b);
  }
  inline void Swap(LidarPointCloud* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LidarPointCloud* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LidarPointCloud* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<LidarPointCloud>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const LidarPointCloud& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const LidarPointCloud& from) {
    LidarPointCloud::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LidarPointCloud* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ds3dmsg.LidarPointCloud";
  }
  protected:
  explicit LidarPointCloud(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPointsFieldNumber = 1,
  };
  // repeated .ds3dmsg.Point points = 1;
  int points_size() const;
  private:
  int _internal_points_size() const;
  public:
  void clear_points();
  ::ds3dmsg::Point* mutable_points(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ds3dmsg::Point >*
      mutable_points();
  private:
  const ::ds3dmsg::Point& _internal_points(int index) const;
  ::ds3dmsg::Point* _internal_add_points();
  public:
  const ::ds3dmsg::Point& points(int index) const;
  ::ds3dmsg::Point* add_points();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ds3dmsg::Point >&
      points() const;

  // @@protoc_insertion_point(class_scope:ds3dmsg.LidarPointCloud)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ds3dmsg::Point > points_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_lidar_5fschema_2eproto;
};
// -------------------------------------------------------------------

class Point final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ds3dmsg.Point) */ {
 public:
  inline Point() : Point(nullptr) {}
  ~Point() override;
  explicit PROTOBUF_CONSTEXPR Point(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Point(const Point& from);
  Point(Point&& from) noexcept
    : Point() {
    *this = ::std::move(from);
  }

  inline Point& operator=(const Point& from) {
    CopyFrom(from);
    return *this;
  }
  inline Point& operator=(Point&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Point& default_instance() {
    return *internal_default_instance();
  }
  static inline const Point* internal_default_instance() {
    return reinterpret_cast<const Point*>(
               &_Point_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Point& a, Point& b) {
    a.Swap(&b);
  }
  inline void Swap(Point* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Point* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Point* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Point>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Point& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Point& from) {
    Point::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Point* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ds3dmsg.Point";
  }
  protected:
  explicit Point(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
    kIntensityFieldNumber = 4,
  };
  // float x = 1;
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // float y = 2;
  void clear_y();
  float y() const;
  void set_y(float value);
  private:
  float _internal_y() const;
  void _internal_set_y(float value);
  public:

  // float z = 3;
  void clear_z();
  float z() const;
  void set_z(float value);
  private:
  float _internal_z() const;
  void _internal_set_z(float value);
  public:

  // float intensity = 4;
  void clear_intensity();
  float intensity() const;
  void set_intensity(float value);
  private:
  float _internal_intensity() const;
  void _internal_set_intensity(float value);
  public:

  // @@protoc_insertion_point(class_scope:ds3dmsg.Point)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    float x_;
    float y_;
    float z_;
    float intensity_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_lidar_5fschema_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// LidarPointCloud

// repeated .ds3dmsg.Point points = 1;
inline int LidarPointCloud::_internal_points_size() const {
  return _impl_.points_.size();
}
inline int LidarPointCloud::points_size() const {
  return _internal_points_size();
}
inline void LidarPointCloud::clear_points() {
  _impl_.points_.Clear();
}
inline ::ds3dmsg::Point* LidarPointCloud::mutable_points(int index) {
  // @@protoc_insertion_point(field_mutable:ds3dmsg.LidarPointCloud.points)
  return _impl_.points_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ds3dmsg::Point >*
LidarPointCloud::mutable_points() {
  // @@protoc_insertion_point(field_mutable_list:ds3dmsg.LidarPointCloud.points)
  return &_impl_.points_;
}
inline const ::ds3dmsg::Point& LidarPointCloud::_internal_points(int index) const {
  return _impl_.points_.Get(index);
}
inline const ::ds3dmsg::Point& LidarPointCloud::points(int index) const {
  // @@protoc_insertion_point(field_get:ds3dmsg.LidarPointCloud.points)
  return _internal_points(index);
}
inline ::ds3dmsg::Point* LidarPointCloud::_internal_add_points() {
  return _impl_.points_.Add();
}
inline ::ds3dmsg::Point* LidarPointCloud::add_points() {
  ::ds3dmsg::Point* _add = _internal_add_points();
  // @@protoc_insertion_point(field_add:ds3dmsg.LidarPointCloud.points)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ds3dmsg::Point >&
LidarPointCloud::points() const {
  // @@protoc_insertion_point(field_list:ds3dmsg.LidarPointCloud.points)
  return _impl_.points_;
}

// -------------------------------------------------------------------

// Point

// float x = 1;
inline void Point::clear_x() {
  _impl_.x_ = 0;
}
inline float Point::_internal_x() const {
  return _impl_.x_;
}
inline float Point::x() const {
  // @@protoc_insertion_point(field_get:ds3dmsg.Point.x)
  return _internal_x();
}
inline void Point::_internal_set_x(float value) {
  
  _impl_.x_ = value;
}
inline void Point::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:ds3dmsg.Point.x)
}

// float y = 2;
inline void Point::clear_y() {
  _impl_.y_ = 0;
}
inline float Point::_internal_y() const {
  return _impl_.y_;
}
inline float Point::y() const {
  // @@protoc_insertion_point(field_get:ds3dmsg.Point.y)
  return _internal_y();
}
inline void Point::_internal_set_y(float value) {
  
  _impl_.y_ = value;
}
inline void Point::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:ds3dmsg.Point.y)
}

// float z = 3;
inline void Point::clear_z() {
  _impl_.z_ = 0;
}
inline float Point::_internal_z() const {
  return _impl_.z_;
}
inline float Point::z() const {
  // @@protoc_insertion_point(field_get:ds3dmsg.Point.z)
  return _internal_z();
}
inline void Point::_internal_set_z(float value) {
  
  _impl_.z_ = value;
}
inline void Point::set_z(float value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:ds3dmsg.Point.z)
}

// float intensity = 4;
inline void Point::clear_intensity() {
  _impl_.intensity_ = 0;
}
inline float Point::_internal_intensity() const {
  return _impl_.intensity_;
}
inline float Point::intensity() const {
  // @@protoc_insertion_point(field_get:ds3dmsg.Point.intensity)
  return _internal_intensity();
}
inline void Point::_internal_set_intensity(float value) {
  
  _impl_.intensity_ = value;
}
inline void Point::set_intensity(float value) {
  _internal_set_intensity(value);
  // @@protoc_insertion_point(field_set:ds3dmsg.Point.intensity)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace ds3dmsg

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_lidar_5fschema_2eproto
